# Generated by Django 5.1.15 on 2026-06-14 12:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('resource_type', models.CharField(choices=[('employee', 'Employee'), ('contractor', 'Contractor'), ('equipment', 'Equipment')], default='employee', max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('capacity_hours_per_week', models.PositiveIntegerField(default=40)),
                ('cost_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_resources', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percent', models.PositiveSmallIntegerField(default=100)),
                ('allocated_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_allocations', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_allocations', to='core.tenant')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='resources.resource')),
            ],
            options={
                'ordering': ['-start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('functional', 'Functional'), ('soft', 'Soft Skill'), ('domain', 'Domain')], default='technical', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_skills', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.skill'),
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('period', models.CharField(max_length=10)),
                ('demand_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('capacity_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('status', models.CharField(choices=[('projected', 'Projected'), ('confirmed', 'Confirmed'), ('closed', 'Closed')], default='projected', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_forecasts', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_demand_forecasts', to='core.tenant')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_forecasts', to='resources.skill')),
            ],
            options={
                'ordering': ['period', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_project', models.CharField(max_length=120)),
                ('is_lead', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('released', 'Released')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_assignments', to='projects.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='resources.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_team_assignments', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('work_date', models.DateField(default=django.utils.timezone.now)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('is_billable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_time_entries', to='projects.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='resources.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_time_entries', to='core.tenant')),
            ],
            options={
                'ordering': ['-work_date', 'id'],
            },
        ),
    ]
