# Generated by Django 5.1.15 on 2026-06-15 19:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('scope', models.CharField(blank=True, max_length=120)),
                ('users_reviewed', models.PositiveIntegerField(default=0)),
                ('findings', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='scheduled', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administration_accessreview_reviewer', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_access_reviews', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('differential', 'Differential'), ('snapshot', 'Snapshot')], default='full', max_length=14)),
                ('schedule', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_backup_jobs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('framework', models.CharField(choices=[('soc2', 'SOC 2'), ('iso27001', 'ISO 27001'), ('gdpr', 'GDPR'), ('hipaa', 'HIPAA'), ('pci_dss', 'PCI DSS')], default='soc2', max_length=12)),
                ('control_id', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant')], default='not_started', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administration_complianceitem_owner', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_compliance_items', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('policy_type', models.CharField(choices=[('password', 'Password'), ('mfa', 'MFA'), ('session', 'Session'), ('ip_allowlist', 'IP Allowlist'), ('data_retention', 'Data Retention'), ('encryption', 'Encryption')], default='password', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('enforcement_level', models.CharField(choices=[('advisory', 'Advisory'), ('enforced', 'Enforced'), ('strict', 'Strict')], default='enforced', max_length=10)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('retired', 'Retired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_security_policies', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('metric_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('cpu', 'CPU'), ('memory', 'Memory'), ('storage', 'Storage'), ('api_latency', 'API Latency'), ('uptime', 'Uptime'), ('queue', 'Queue')], default='cpu', max_length=12)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_system_health_metrics', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
