# Generated by Django 5.1.15 on 2026-06-14 12:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('milestone_type', models.CharField(choices=[('milestone', 'Milestone'), ('phase_gate', 'Phase Gate')], default='milestone', max_length=12)),
                ('gate_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('entry_criteria', models.TextField(blank=True)),
                ('exit_criteria', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_milestones', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_milestones', to='core.tenant')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('baseline_date', models.DateField(blank=True, null=True)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_finish', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=12)),
                ('is_current', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_baselines', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_schedule_baselines', to='core.tenant')),
            ],
            options={
                'ordering': ['-baseline_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('effort_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('estimate_method', models.CharField(choices=[('analogous', 'Analogous'), ('parametric', 'Parametric'), ('bottom_up', 'Bottom-Up'), ('three_point', 'Three-Point')], default='bottom_up', max_length=14)),
                ('percent_complete', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=12)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_tasks', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_schedule_tasks', to='core.tenant')),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], default='FS', max_length=2)),
                ('lag_days', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_links', to='planning.scheduletask')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='planning.scheduletask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_task_dependencies', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('estimated_effort_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_packages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='planning.workpackage')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_packages', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_work_packages', to='core.tenant')),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='work_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_tasks', to='planning.workpackage'),
        ),
    ]
