# Generated by Django 5.1.15 on 2026-06-14 15:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('fiscal_year', models.CharField(blank=True, max_length=9)),
                ('category', models.CharField(choices=[('labor', 'Labor'), ('material', 'Material'), ('overhead', 'Overhead'), ('contingency', 'Contingency'), ('equipment', 'Equipment')], default='labor', max_length=12)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgeting_budgets_owned', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgeting_budgets', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgeting_budgets', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('change_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('reallocation', 'Reallocation')], default='increase', max_length=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='pending', max_length=12)),
                ('decided_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='budgeting.budget')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgeting_budget_changes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgeting_budget_changes', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('bac', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('earned_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_accounts', to='budgeting.budget')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgeting_control_accounts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgeting_control_accounts', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgeting_control_accounts', to='core.tenant')),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CostForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('period', models.CharField(max_length=10)),
                ('bac', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('eac', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('etc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('method', models.CharField(choices=[('cpi_based', 'CPI-Based'), ('manual', 'Manual'), ('spi_cpi', 'SPI×CPI')], default='cpi_based', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_forecasts', to='budgeting.budget')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgeting_cost_forecasts', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgeting_cost_forecasts', to='core.tenant')),
            ],
            options={
                'ordering': ['period', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('labor', 'Labor'), ('material', 'Material'), ('travel', 'Travel'), ('equipment', 'Equipment'), ('other', 'Other')], default='material', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('expense_type', models.CharField(choices=[('commitment', 'Commitment'), ('actual', 'Actual')], default='actual', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budgeting.controlaccount')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgeting_expenses', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgeting_expenses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgeting_expenses', to='core.tenant')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
